# Generated by Django 5.0.7 on 2024-09-22 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('isFirstLogin', models.BooleanField(default=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('interested_in', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('images', models.JSONField(default=list)),
                ('bio', models.CharField(blank=True, max_length=300, null=True)),
                ('ageRange', models.JSONField(default=[18, 21])),
                ('distance', models.PositiveIntegerField(default=25)),
                ('likes', models.JSONField(default=list)),
                ('matches', models.JSONField(default=list)),
                ('blacklist', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_profile',
            },
        ),
    ]
