# Generated by Django 5.0.7 on 2024-09-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='room_id',
            field=models.JSONField(default=list),
        ),
    ]
