# Generated by Django 5.0.7 on 2024-09-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_bio_profile_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_title',
        ),
    ]
