# Generated by Django 5.0.7 on 2024-09-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ageRange',
            field=models.JSONField(default=[18, 21]),
        ),
        migrations.AddField(
            model_name='profile',
            name='distance',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
