# Generated by Django 5.0.7 on 2024-09-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blacklist',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='matches',
            field=models.JSONField(default=list),
        ),
    ]
