# Generated by Django 5.0.7 on 2024-09-17 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_blacklist_profile_likes_profile_matches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blacklist',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='matches',
        ),
        migrations.AddField(
            model_name='profile',
            name='blacklist',
            field=models.ManyToManyField(blank=True, related_name='blacklisted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='matched_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
