# Generated by Django 5.0.7 on 2024-09-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_profile_blacklist_remove_profile_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blacklist',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='matches',
        ),
        migrations.AddField(
            model_name='profile',
            name='blacklist',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='matches',
            field=models.JSONField(default=list),
        ),
    ]
