# Generated by Django 5.0.7 on 2024-09-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_room_chat_delete_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='room',
        ),
        migrations.AddField(
            model_name='chat',
            name='room_id',
            field=models.CharField(default='default_room', max_length=255),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
