# Generated by Django 5.0.7 on 2024-09-29 07:21

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=0.5, size=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='message',
            name='room_id',
            field=models.CharField(default='default_room', max_length=255),
        ),
    ]
