# Generated by Django 5.0.7 on 2024-09-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_remove_message_content_remove_message_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
