# Generated by Django 5.0.7 on 2024-09-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0008_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
