# Generated by Django 5.0.7 on 2024-09-30 07:10

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0010_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=0.5, size=None, upload_to='images'),
        ),
    ]
