# Generated by Django 5.0.7 on 2024-10-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0011_message_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
