# Generated by Django 5.0.7 on 2024-10-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0013_imageupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
