# Generated by Django 5.0.7 on 2024-10-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0016_imageupload_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='room_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
