# Generated by Django 5.0.7 on 2024-10-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0017_alter_imageupload_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.TextField(),
        ),
    ]
